id: I8B62CCCC
legacy_id: P005569
ocr_import_info:
  bdrc_scan_id: W27912
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T03:26:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T08:07:21.023749+00:00'
last_modified: 2022-09-02 16:07:51.515932
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W27912
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW27912
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: ཆོས་སྤྱོད་བསྡུས་པ་ཕན་བདེའི་དགའ་སྟོན།
statistics:
  ocr_word_mean_confidence_index: 0.7998333352066669
  ocr_word_median_confidence_index: 0.8899999856948853
quality: null
bases:
  I4513:
    source_metadata:
      id: http://purl.bdrc.io/resource/I4513
      total_pages: 308
      volume_number: 1
      volume_pages_bdrc_intro: 0
    order: 1
    base_file: I4513.txt
    statistics:
      ocr_word_median_confidence_index: 0.8899999856948853
      ocr_word_mean_confidence_index: 0.7998333352066669
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
